dist: trusty
language: java
jdk:
  - openjdk21
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/your-webhook-url
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
after_success:
  - coveralls
install: mvn package -Dgpg.skip=true
